[package]
name = "cosmic_gardener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2" # Check for the latest version of Bevy
rand = "0.8.5"